name: publish to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Pack SDK
        run: |
          dotnet pack SDK --configuration Release

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./SDK/bin/Release/FSTNetwork.LOC.Logic.SDK.*.nupkg \
              --api-key ${{ secrets.NUGET_KEY }} \
              --source ${{ vars.NUGET_SOURCE }} \
              --skip-duplicate
